before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libXxf86vm-dev libopenal1 libopenal-dev libvorbis-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DCMAKE_C_FLAGS=-fPIC -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
  - make
  - sudo make install
  - cd ..
  - curl -s https://static.rust-lang.org/rustup.sh | sudo -E sh
  - rustc -v
script:
  - cargo build
